apiVersion: v1
kind: Pod
metadata:
  labels:
  name: rezex
spec:
  containers:
  - name: rezex
    image: glennswest/rezex:8084378
    args:
    - /server
    livenessProbe: 
      httpGet:   
        # host: my-host
        # scheme: HTTPS
        path: /healthz
        port: 8080
      initialDelaySeconds: 15  
      timeoutSeconds: 1   
    name: liveness   

