apiVersion: v1
kind: Pod
metadata:
  labels:
  name: rezex
spec:
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 30
    - key: node.kubernetes.io/unknown
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 30
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 30
  containers:
  - name: rezex
    image: glennswest/rezex:8084378
    args:
    - /server
    livenessProbe: 
      httpGet:   
        # host: my-host
        # scheme: HTTPS
        path: /healthz
        port: 8080
      initialDelaySeconds: 15  
      timeoutSeconds: 1   
    name: liveness   
